#! /bin/python3
from __future__ import print_function

import sys, os, re
from random import *

def shuffle(): return sample(range(52),52)

suit = 'cdhs'
rank = '23456789TJQKA'

def c2v(card): return	((card&3) << 4) + (card>>2)

def v2s(valu): return	'%c%c' % (rank[valu & 15], suit[valu >> 4])

def dist(hand):
	global rev
	freq = [0,0,0,0]
	for card in hand: freq[card & 3] += 1
	return	'%d%d%d%d' % tuple(sorted(freq,reverse=rev))

rev = 1
def main():
	global rev
	histo = dict()
	argc = len(sys.argv)
	reps = 100 if argc <= 1 else int(sys.argv[1])
	fld  = 1   if argc <= 2 else int(sys.argv[2])
	rev  = 1   if argc <= 3 else int(sys.argv[3])
	cent = 25.0/reps	# 100 divided by 4 Hands per Deal
	print('args: %r, Deals: %d, Field: %s, Sort: %s' %
		(sys.argv, reps, ('Dist','Count')[fld], ('Up', 'Down') [rev]))
	while	reps:
		reps -= 1
		deal = shuffle()
		nort = deal[00:13]
		east = deal[13:26]
		suds = deal[26:39]
		west = deal[39:52]

		key = dist(nort); histo[key] = histo.get(key,0) + 1
		key = dist(east); histo[key] = histo.get(key,0) + 1
		key = dist(suds); histo[key] = histo.get(key,0) + 1
		key = dist(west); histo[key] = histo.get(key,0) + 1

	print('Rank (Dist, Count)\tPercent\tTotals\tReverse')
	cum = 0.0; seq = 1
	for	item in sorted(histo.items(), key=lambda x: int(x[fld]), reverse=rev):
		pct = item[1] * cent
		print('%3d ' % seq, item, 
			'\t%6.3f\t%6.3f\t%6.3f' % (pct, cum, 100.0 - cum))
		cum += pct; seq += 1

if __name__ == '__main__': main()
