#! /bin/python3
from __future__ import print_function

import sys, os, re
from random import *

def shuffle(): return sample(range(52),52)

suit = 'cdhs'
rank = '23456789TJQKA'
rev = 1

def c2v(card): return	((card&3) << 4) + (card>>2)

def v2s(valu): return	'%c%c' % (rank[valu & 15], suit[valu >> 4])

def dist(hand):
	global rev
	freq = [0,0,0,0]
	for card in hand: freq[card & 3] += 1
	return	int('%x%x%x%x' % tuple(sorted(freq,reverse=rev)), base=16)

def main():
	global rev
	histo = dict()
	argc = len(sys.argv)
	reps = 1000 if argc <= 1 else int(sys.argv[1])
	fld  = 1    if argc <= 2 else int(sys.argv[2])
	rev  = 1    if argc <= 3 else int(sys.argv[3])
	cent = 50.0/reps	# 100 divided by 2 Sides per Deal
	print('args: %r, Deals: %d, Field: %s, Sort: %s' %
		(sys.argv, reps, ('Dist','Count')[fld], ('Up', 'Down')[rev]))
	while	reps:
		reps -= 1
		deal = shuffle()
		nort = deal[00:26]	# N+E cards
		east = deal[13:26]
		suds = deal[26:39]
		west = deal[26:52]	# W+S cards

		key = dist(nort); histo[key] = histo.get(key,0) + 1
		#ey = dist(east); histo[key] = histo.get(key,0) + 1
		#ey = dist(suds); histo[key] = histo.get(key,0) + 1
		key = dist(west); histo[key] = histo.get(key,0) + 1

	#rint('12345678' * 9)
	print('Rank\tDist\t Count\tSubtot\tPercent\tReverse')
	cum = 0.0; seq = 1
	for	item in sorted(histo.items(), key=lambda x: int(x[fld]), reverse=rev):
		pct = item[1] * cent
		print('%4d' % seq, '%04X' % item[0], '%6d' % item[1], 
			'%6.3f' % cum,
			'%6.3f' % pct,
			'%6.3f' % (100.0 - cum), sep='\t')
		cum += pct; seq += 1

if __name__ == '__main__': main()
