#! /bin/python3
from __future__ import print_function

import sys, os, re
from random import *

def shuffle(): return sample(range(52),52)

def show(deal):
	peeps = ('North', 'East', 'South', 'West')
	zoots = ('Spades', 'Hearts', 'Diamond', 'Clubs')
	suits = 'SHDC'
	ranks = '23456789TJQKA'

	base = 0
	data = [[ '' for s in suits] for r in range(4)]
	print(('%s\t' * 5) % ('', *zoots))
	for hand in range(4):
		for card in sorted(deal[base:base+13], reverse=True):
			suit = card &  3
			rank = card // 4
			data[hand][suit] += ranks[rank]
		print(('%s\t' * 5) % (peeps[hand], *data[hand]))
		base += 13
	
argc = len(sys.argv)
reps = 1 if argc <= 1 else int(sys.argv[1])

while reps > 0: reps -=1; show(shuffle())
